import json
import google.generativeai as genai
from typing import Optional
from src.domain.schemas.timeline import CanonicalTimeline

class GeminiRefiner:
    """
    Uses Google's Gemini models to refine rule-based segmentation,
    improving punctuation, capitalization, and minor grammatical anomalies
    while preserving the canonical timeline structure and exact word timings.
    """
    
    def __init__(self, api_key: str, model_name: str = "gemini-2.5-flash"):
        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel(model_name)
        
    def process(self, timeline: CanonicalTimeline) -> CanonicalTimeline:
        """
        Takes a deterministically chunked timeline and asks Gemini 
        to apply proper capitalization and punctuation to the segment texts.
        """
        if not timeline.segments:
            return timeline
            
        # We prepare a structured payload for Gemini to ensure we map back reliably
        payload_to_refine = [
            {"id": seg.id, "text": seg.text} for seg in timeline.segments
        ]
        
        prompt = (
            "You are a captioning assistant. You are given a JSON array of caption segments (text mapped to an ID) "
            "that were generated by an ASR without proper punctuation or capitalization.\n\n"
            "Your task is to return a JSON array containing the exact same IDs, but with the 'text' field properly "
            "punctuated and capitalized (e.g. adding periods, commas, question marks). "
            "DO NOT change the underlying words or add new words, only alter punctuation and casing.\n\n"
            "Input:\n"
            + json.dumps(payload_to_refine) +
            "\n\nOutput ONLY valid JSON."
        )
        
        try:
            response = self.model.generate_content(prompt)
            response_text = response.text
            
            # Clean up potential markdown blocks from Gemini
            if response_text.startswith("```json"):
                response_text = response_text[7:]
            if response_text.startswith("```"):
                response_text = response_text[3:]
            if response_text.endswith("```"):
                response_text = response_text[:-3]
                
            refined_data = json.loads(response_text.strip())
            
            # Map the refined text back to the timeline segments
            refinement_map = {item["id"]: item["text"] for item in refined_data if "id" in item and "text" in item}
            
            for seg in timeline.segments:
                if seg.id in refinement_map:
                    seg.text = refinement_map[seg.id]
                    # Also update the first word casing and last word punctuation 
                    # as a basic sync back to word level (optional, but good for rendering)
                    
            timeline.provenance.segmentation_method = "rule_based_chunking_with_gemini_refinement"
            
        except Exception as e:
            print(f"Gemini Refinement Failed, falling back to original: {e}")
            
        return timeline
